version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: benghazi_postgres
    restart: always
    environment:
      POSTGRES_DB: surakshadb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/1_db_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:



# psql "host=127.0.0.1 port=5432 dbname=surakshadb user=user password=password"